spring:
  application:
    name: test-service
server:
  port: 8001
#eureka:
#  client:
#    registerWithEureka: true
#    service-url:
##      defaultZone: http://localhost:8000/eureka/
#      defaultZone: http://eureka.didispace.com/eureka/