spring:
  application:
    name: consumer-client
server:
  port: 8003

#eureka:
#  client:
#    registerWithEureka: true
#    service-url:
#      defaultZone: http://eureka.didispace.com/eureka/

ribbon:
  eureka:
    enabled: false

test-service:
  ribbon:
    listOfServers: localhost:8001,localhost:8002
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule