spring:
  application:
    name: consumer-client
server:
  port: 8011


#eureka:
#  client:
#    registerWithEureka: true
#    service-url:
#      defaultZone: http://eureka.didispace.com/eureka/

# 直接操作文件

ribbon:
  eureka:
    enabled: false
  listOfServers: localhost:8001
  ConnectTimeout: 1000

test-service-a:
  ribbon:
    NFLoadBalancerClassName: com.netflix.loadbalancer.DynamicServerListLoadBalancer
    listOfServers: localhost:8002
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ReadTimeout: 3000
    ConnectTimeout: 5000

test-service-b:
  ribbon:
    NFLoadBalancerClassName: com.netflix.loadbalancer.DynamicServerListLoadBalancer
    listOfServers: localhost:8003
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    ReadTimeout: 6000
    ConnectTimeout: 10000